In [1]:
import os
import sys
from dotenv import load_dotenv, find_dotenv

In [2]:
import json

In [3]:
import pandas as pd
import numpy as np

In [4]:
DATA_FOLDER_PATH = os.path.join(os.path.dirname(os.getcwd()), "data","deploy3")
DEPLOY1_FOLDER_PATH = os.path.join(os.path.dirname(os.getcwd()), "data","deploy1")
SCAN_FOLDER_PATH = os.path.join(os.path.dirname(os.getcwd()), "streamlit","scan")
STREAMLIT_FOLDER_PATH = os.path.join(os.path.dirname(os.getcwd()), "streamlit")

In [5]:
players = pd.read_pickle(os.path.join(DATA_FOLDER_PATH, "final","players.pkl"))

In [6]:
players.head()

,burners,burnerParent,totalWins,totalLosses,totalGasEarned,totalGasLost,totalGames,totalRevenue
0,0x3FE255c4d125290977f5583F849040416CCE938c,0xE830F2785E2C4abbE8B9BCA738Efd6DE50D0CB86,33.0,58.0,3.3640,5.80,91.0,-2.4360
1,0x7141Bd2E038cc89E8D3c4dA6d87740949dF40212,0x7A1f11FF4d3a14452090b28Ea09Fe40F0cA94f81,16.0,41.0,2.1240,4.10,57.0,-1.9760
2,0x44a1Eb48c93B6297Dbf43B8896A2e793610B756d,0x512F753e1bF0b846de1FCdEbCEecab1CEa603E6d,27.0,27.0,2.7880,2.70,54.0,0.0880
3,0x0821B1252c07Ab360F432f90e9a8e6DE98A86259,0x7Bfc71D0433D57c6c8a474A411FDA0f692344D94,23.0,20.0,2.5020,2.00,43.0,0.5020
4,0x5e2cD87941B43d8091C84e9B032101a3215c63E2,0x14576E03188F7DF78c62B8F9F5B4CA1EBF16a219,14.0,28.0,3.3796,5.11,42.0,-1.7304

In [7]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35708 entries, 0 to 35707
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   burners         35708 non-null  object
 1   burnerParent    35708 non-null  object
 2   totalWins       35708 non-null  float64
 3   totalLosses     35708 non-null  float64
 4   totalGasEarned  35708 non-null  float64
 5   totalGasLost    35708 non-null  float64
 6   totalGames      35708 non-null  float64
 7   totalRevenue    35708 non-null  float64
dtypes: float64(6), object(2)
memory usage: 2.2+ MB

In [8]:
deploy1 = pd.read_pickle(os.path.join(DEPLOY1_FOLDER_PATH,"players.pkl"))

In [9]:
deploy1.head()

,burners,burnerParent,totalWins,totalLosses,totalGasEarned,totalGasLost,totalGames,totalRevenue
0,0x24bF54A5Ce74e589Bc192518d76b75959886346d,0xB8eb412990236ebb933675C8b5C4cc9812B69dED,2.0,3.0,0.584,0.3,5.0,0.284
1,0xfE3e6ab5d787F4099478Bbe811a740d903E219fb,0x0000000000000000000000000000000000000000,1.0,4.0,0.584,0.5,5.0,0.084
2,0x100b782936498F640c8Df54ab57bfd2186F0f002,0x4EE6a67a9DDeD0c4c74FD9Ee4E2D83D03bf50A94,0.0,5.0,0.000,0.5,5.0,-0.500
3,0x16f6AfF7A2D84B802b2ddF0F0AeD49033B69F4f9,0x0000000000000000000000000000000000000000,1.0,3.0,0.096,0.3,4.0,-0.204
4,0x6cF9E3ADF2c0FaB32C6f19c112dB62239DeBc049,0x7C898Dd66e27Cc82C87Ddbe0dB3093308DaF27fd,2.0,2.0,0.584,0.2,4.0,0.384

In [10]:
deploy1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 177 entries, 0 to 176
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   burners         177 non-null    object
 1   burnerParent    177 non-null    object
 2   totalWins       177 non-null    float64
 3   totalLosses     177 non-null    float64
 4   totalGasEarned  177 non-null    float64
 5   totalGasLost    177 non-null    float64
 6   totalGames      177 non-null    float64
 7   totalRevenue    177 non-null    float64
dtypes: float64(6), object(2)
memory usage: 11.2+ KB

In [11]:
finalPlayers = pd.concat([players, deploy1],ignore_index=True)

In [12]:
finalPlayers = finalPlayers.sort_values(["burnerParent","totalGames"], ascending = [False, False])
finalPlayers.reset_index(drop=True,inplace=True)
print(finalPlayers.info())
finalPlayers.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35885 entries, 0 to 35884
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   burners         35885 non-null  object
 1   burnerParent    35885 non-null  object
 2   totalWins       35885 non-null  float64
 3   totalLosses     35885 non-null  float64
 4   totalGasEarned  35885 non-null  float64
 5   totalGasLost    35885 non-null  float64
 6   totalGames      35885 non-null  float64
 7   totalRevenue    35885 non-null  float64
dtypes: float64(6), object(2)
memory usage: 2.2+ MB
None

,burners,burnerParent,totalWins,totalLosses,totalGasEarned,totalGasLost,totalGames,totalRevenue
0,0xeedb9220C43f29Bd807Fd2c092c0EFA841F67ED4,0xfff069C7de69b4433050E7AaeaB4BB198541DF56,1.0,4.0,0.292,1.3,5.0,-1.008
1,0x9093470d431257D665687D97F22f0Db64408E03D,0xffe52c5e9cFddd7A538c430880d7778531EB0d01,1.0,0.0,0.096,0.0,1.0,0.096
2,0x08498E4644A02b84a3b674150a663C3B3CBe729A,0xffb58E2364a07D2fC43C008E32d492b99EcA60f9,0.0,1.0,0.000,0.1,1.0,-0.100
3,0xCb75970cd756b4a61011e0769f2299529d7ca1C6,0xffb0A17E69CB382175503cfe0B029b179658a06A,1.0,1.0,0.096,0.1,2.0,-0.004
4,0x211287fFe9EB23B15901423A161f2a2100c2D67B,0xffa6FE7969c3B2eF11D1A7dEA26fD525B08F0540,1.0,0.0,0.194,0.0,1.0,0.194
5,0x4eFCE49177BA93E0d103C2e97f9446eEc67Ebd1b,0xffC43AAF9c2757BedF25155735B7d886093279bB,0.0,1.0,0.000,0.1,1.0,-0.100
6,0x05B561cCffc11e0818B377e64060a422646ab167,0xffC34FA587345848D6cF72575398ef27011feBA5,0.0,1.0,0.000,0.1,1.0,-0.100
7,0xfBcEAf800c61DADCB744feAC9A3217EB060A6787,0xffC2cE9c18A1fEf310BF0C99D902aED6f38361d2,0.0,4.0,0.000,0.4,4.0,-0.400
8,0xf28dd0955d7e401f55eD1556EB0b09d154Fe672D,0xffAc03c56bA2dA653ea36F8220b0F99BFD539053,1.0,2.0,0.292,0.2,3.0,0.092
9,0x9F850E4613509f54d06B2DCF860CA7fC3090ab97,0xff9Ce7Ba78445F1882A6aC5bcA5f87306613FE0f,4.0,14.0,0.384,1.4,18.0,-1.016

In [48]:
#19481 - 1599 (those with no parent) = 17882

,burners,burnerParent,totalWins,totalLosses,totalGasEarned,totalGasLost,totalGames,totalRevenue
0,0xeedb9220C43f29Bd807Fd2c092c0EFA841F67ED4,0xfff069C7de69b4433050E7AaeaB4BB198541DF56,1.0,4.0,0.292,1.3,5.0,-1.008
1,0xCb75970cd756b4a61011e0769f2299529d7ca1C6,0xffb0A17E69CB382175503cfe0B029b179658a06A,1.0,1.0,0.096,0.1,2.0,-0.004
2,0x4eFCE49177BA93E0d103C2e97f9446eEc67Ebd1b,0xffC43AAF9c2757BedF25155735B7d886093279bB,0.0,1.0,0.000,0.1,1.0,-0.100
3,0x37Bd449B9e6Cfde37d2242d83D3164a25d3d8132,0xff8FBcf1Cb1cBa9C2714894332251808456cCa90,0.0,1.0,0.000,0.1,1.0,-0.100
4,0x181013F3dDF8F6Cc041c2da48055916d2916aF2e,0xff77d744410d38Ec7DF31569eE0489722FF39929,0.0,1.0,0.000,0.1,1.0,-0.100
...,...,...,...,...,...,...,...,...
17877,0x4Ee5975FF8a66d8FA591CaE7DA2e684361070854,0x000025B47899B3fc97383a65510C8e84389B1490,1.0,7.0,0.194,0.7,8.0,-0.506
17878,0x6455961d84F418a5F4574529FAcf6532d0291798,0x00000E0e2E6298505A639A340845F60a0eeA8528,0.0,1.0,0.000,0.1,1.0,-0.100
17879,0x1E5570ab680Fa67434954e973E0c8B695c255Cb8,0x000000a584697755A0378444f34FEc06229B7E38,2.0,2.0,0.486,0.2,4.0,0.286
17880,0x8c49f23f54b6307f8B5b0D49B288003C2845b2F3,0x0000001089167600c25258Da29d2e2c857ec1689,1.0,0.0,1.940,0.0,1.0,1.940
17881,0xC4d572dfe8B6D369d7F5bF40e78AAB012b5d1a67,0x000000006F457c0f8F560333d9c2877287d92a92,0.0,1.0,0.000,0.1,1.0,-0.100

In [13]:
finalPlayersWithParentBurner = finalPlayers[finalPlayers["burnerParent"] !="0x0000000000000000000000000000000000000000"]
print(finalPlayersWithParentBurner.info())
finalPlayersWithParentBurner.sort_values(by=["burnerParent", "totalGames"],ascending=[False,False],inplace=True)
finalPlayersWithParentBurner.head(10)

<class 'pandas.core.frame.DataFrame'>
Index: 34145 entries, 0 to 34144
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   burners         34145 non-null  object
 1   burnerParent    34145 non-null  object
 2   totalWins       34145 non-null  float64
 3   totalLosses     34145 non-null  float64
 4   totalGasEarned  34145 non-null  float64
 5   totalGasLost    34145 non-null  float64
 6   totalGames      34145 non-null  float64
 7   totalRevenue    34145 non-null  float64
dtypes: float64(6), object(2)
memory usage: 2.3+ MB
None

/tmp/ipykernel_55183/3616447075.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  finalPlayersWithParentBurner.sort_values(by=["burnerParent", "totalGames"],ascending=[False,False],inplace=True)

,burners,burnerParent,totalWins,totalLosses,totalGasEarned,totalGasLost,totalGames,totalRevenue
0,0xeedb9220C43f29Bd807Fd2c092c0EFA841F67ED4,0xfff069C7de69b4433050E7AaeaB4BB198541DF56,1.0,4.0,0.292,1.3,5.0,-1.008
1,0x9093470d431257D665687D97F22f0Db64408E03D,0xffe52c5e9cFddd7A538c430880d7778531EB0d01,1.0,0.0,0.096,0.0,1.0,0.096
2,0x08498E4644A02b84a3b674150a663C3B3CBe729A,0xffb58E2364a07D2fC43C008E32d492b99EcA60f9,0.0,1.0,0.000,0.1,1.0,-0.100
3,0xCb75970cd756b4a61011e0769f2299529d7ca1C6,0xffb0A17E69CB382175503cfe0B029b179658a06A,1.0,1.0,0.096,0.1,2.0,-0.004
4,0x211287fFe9EB23B15901423A161f2a2100c2D67B,0xffa6FE7969c3B2eF11D1A7dEA26fD525B08F0540,1.0,0.0,0.194,0.0,1.0,0.194
5,0x4eFCE49177BA93E0d103C2e97f9446eEc67Ebd1b,0xffC43AAF9c2757BedF25155735B7d886093279bB,0.0,1.0,0.000,0.1,1.0,-0.100
6,0x05B561cCffc11e0818B377e64060a422646ab167,0xffC34FA587345848D6cF72575398ef27011feBA5,0.0,1.0,0.000,0.1,1.0,-0.100
7,0xfBcEAf800c61DADCB744feAC9A3217EB060A6787,0xffC2cE9c18A1fEf310BF0C99D902aED6f38361d2,0.0,4.0,0.000,0.4,4.0,-0.400
8,0xf28dd0955d7e401f55eD1556EB0b09d154Fe672D,0xffAc03c56bA2dA653ea36F8220b0F99BFD539053,1.0,2.0,0.292,0.2,3.0,0.092
9,0x9F850E4613509f54d06B2DCF860CA7fC3090ab97,0xff9Ce7Ba78445F1882A6aC5bcA5f87306613FE0f,4.0,14.0,0.384,1.4,18.0,-1.016

In [14]:
# output FinalPlayersWithBurners
finalPlayersWithParentBurner.to_pickle("finalWithParents13102023.pkl")

In [15]:
finalPlayersWithParentBurner.to_csv("finalWithParents13102023.csv",index=False)

In [16]:
# get totals for parent burner
parentBurnerStats = finalPlayersWithParentBurner.groupby("burnerParent")[["totalWins","totalLosses", "totalGasEarned", "totalGasLost", "totalGames", "totalRevenue"
                                                                         ]].sum().reset_index()
print(parentBurnerStats.info())
parentBurnerStats.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33604 entries, 0 to 33603
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   burnerParent    33604 non-null  object
 1   totalWins       33604 non-null  float64
 2   totalLosses     33604 non-null  float64
 3   totalGasEarned  33604 non-null  float64
 4   totalGasLost    33604 non-null  float64
 5   totalGames      33604 non-null  float64
 6   totalRevenue    33604 non-null  float64
dtypes: float64(6), object(1)
memory usage: 1.8+ MB
None

,burnerParent,totalWins,totalLosses,totalGasEarned,totalGasLost,totalGames,totalRevenue
0,0x000000006F457c0f8F560333d9c2877287d92a92,0.0,2.0,0.000,0.2,2.0,-0.200
1,0x00000008Ba1350e10F55a208C0C449F7d07be5B0,0.0,1.0,0.000,0.1,1.0,-0.100
2,0x0000001089167600c25258Da29d2e2c857ec1689,1.0,0.0,1.940,0.0,1.0,1.940
3,0x000000a584697755A0378444f34FEc06229B7E38,2.0,5.0,0.486,0.5,7.0,-0.014
4,0x00000E0e2E6298505A639A340845F60a0eeA8528,0.0,1.0,0.000,0.1,1.0,-0.100
5,0x000025B47899B3fc97383a65510C8e84389B1490,1.0,7.0,0.194,0.7,8.0,-0.506
6,0x00009B30097B18aD52511E469cD6d626BD3503AE,1.0,0.0,0.292,0.0,1.0,0.292
7,0x0000CE08fa224696A819877070BF378e8B131ACF,1.0,0.0,0.584,0.0,1.0,0.584
8,0x0000d62c80919FEF4E44Ed4C283A71E8EA908f68,1.0,2.0,0.096,0.2,3.0,-0.104
9,0x0001215991d2C96245d80FAC57d9dc0Cc6FAE05b,0.0,2.0,0.000,0.2,2.0,-0.200

In [17]:
complete1Games = parentBurnerStats[parentBurnerStats["totalGames"]>0]
complete1Games.to_csv("complete1Games13102023.csv", index=False)

In [18]:
complete3Games = parentBurnerStats[parentBurnerStats["totalGames"]>2]
complete3Games.to_csv("complete3Games13102023.csv", index=False)

In [19]:
totalWins1Games = parentBurnerStats[parentBurnerStats["totalWins"]>0]
totalWins1Games.to_csv("totalWins1orMore13102023.csv", index=False)

In [20]:
countUnique = finalPlayersWithParentBurner.groupby("burnerParent")["burners"].count().to_frame().reset_index().sort_values(by="burners",ascending=False)
countUnique

                                     burnerParent  burners
12144  0x5ECa6CE07dC82E150F23A988d2f6B29631ae2Dbc        5
12344  0x5c1115B1b81df25FB220Aac2c29EDCfE55419ff7        5
31087  0xd92bd3c2e27A5286d82C63D7D4c483B8f5f3D322        4
17573  0x873eABb2c1F6a94Dd249edC1cd78cC685f750b22        3
21364  0xA86e8A5f57fFDE75cE14C52E5fF07b6be8c9245c        3
...                                           ...      ...
11273  0x562915D42731686a63Ab83A060c1393138E8fC68        1
11272  0x5628950f62B7dcac2a70F5b9115f6b2A79B9885a        1
11271  0x56284a5aA9c58C97e1a042A3da47512Cb2173d06        1
11270  0x5623FBAEF16f232f5097bE78E52a6b44aC9Ff503        1
33603  0xfff069C7de69b4433050E7AaeaB4BB198541DF56        1

[33604 rows x 2 columns]