In [2]:
import os
import sys
from dotenv import load_dotenv, find_dotenv

In [3]:
import json

In [4]:
import pandas as pd
import numpy as np

In [5]:
DATA_FOLDER_PATH = os.path.join(os.path.dirname(os.getcwd()), "data","deploy5")
DEPLOY1_FOLDER_PATH = os.path.join(os.path.dirname(os.getcwd()), "data","deploy1")
SCAN_FOLDER_PATH = os.path.join(os.path.dirname(os.getcwd()), "streamlit","scan")
STREAMLIT_FOLDER_PATH = os.path.join(os.path.dirname(os.getcwd()), "streamlit")

In [6]:
players = pd.read_pickle(os.path.join(DATA_FOLDER_PATH, "final","players.pkl"))

In [7]:
players.head()

,burners,burnerParent,totalWins,totalLosses,totalGasEarned,totalGasLost,totalGames,totalRevenue
0,0x3b44a30f9c125efC059caCb44f9Bbe2e3Fd94DFC,0xB32970743a239397e9cfe02a1D86eb4B734098DB,103.0,143.0,10.476,14.3,246.0,-3.824
1,0x4c0aBC4242e72Ae4c1431267e7Ab9EFfb516F1e9,0x03CE28D064cBFAcD218E37481AfC4606FcB518B4,13.0,129.0,3.698,12.9,142.0,-9.202
2,0x3FE255c4d125290977f5583F849040416CCE938c,0xE830F2785E2C4abbE8B9BCA738Efd6DE50D0CB86,33.0,58.0,3.364,5.8,91.0,-2.436
3,0x44a1Eb48c93B6297Dbf43B8896A2e793610B756d,0x512F753e1bF0b846de1FCdEbCEecab1CEa603E6d,31.0,43.0,3.172,4.3,74.0,-1.128
4,0x7141Bd2E038cc89E8D3c4dA6d87740949dF40212,0x7A1f11FF4d3a14452090b28Ea09Fe40F0cA94f81,16.0,41.0,2.124,4.1,57.0,-1.976

In [8]:
players.tail(10)

,burners,burnerParent,totalWins,totalLosses,totalGasEarned,totalGasLost,totalGames,totalRevenue
78396,0x1417Ce8701314cA023aDb8660286c003E8f9B67b,0xF286F0728bec871951E642C464e4d0347a923569,0.0,1.0,0.0,0.10,1.0,-0.10
78397,0x14136e93AbFF48c4deB7984c031371705E01E0B8,0x86A2F37cd1C0ff17599A20f6fa446abBc118AF27,0.0,1.0,0.0,0.10,1.0,-0.10
78398,0x13e4e94f1E1043145571Bbcd44ed8DBdcD281388,0x591E10d6741d9C5E166e3091182eFD3132893c21,0.0,1.0,0.0,0.12,1.0,-0.12
78399,0x14Ddceb3d7E293b348e9eB38cd5438F5Df58Ef39,0x957c68F39E9d13DeeFDAEc033072b8a1d1798c09,0.0,1.0,0.0,0.10,1.0,-0.10
78400,0x14EA63A81f95B058e580581D7B4bd2f8c27d142d,0xFaDdF8E5E87B15c225c09DA28dc0A9BD8ba7af29,0.0,1.0,0.0,0.10,1.0,-0.10
78401,0x4434747d375a53cB57A43f578EA045458C54222a,0x76C5762E65cB28B928466256C680F5342C4Ad234,0.0,0.0,0.0,0.00,0.0,0.00
78402,0x1B0eDb82359e811a4934aaDF6Be51f293c1AE803,0xb139A58Ab474a90Da3E0336E6b01791ef1A170Bd,0.0,0.0,0.0,0.00,0.0,0.00
78403,0xE49AD4C7459299C0e1B2b5DA568e1642b5cc26B5,0xb1013fcEfE0b2168f920D0b89f122418a1d89E34,0.0,0.0,0.0,0.00,0.0,0.00
78404,0x9B29c8a4314F5e54AE891370Aebad969F6FB43d4,0x90Ee5b93430d9C368eD7e45b40FC2918747CEDaF,0.0,0.0,0.0,0.00,0.0,0.00
78405,0xde083e5FC0b840463459C621fd6e1cFa5fE6e677,0xFF3588411E280DF2a2CdB256BC0108DcEE551FC5,0.0,0.0,0.0,0.00,0.0,0.00

In [9]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78406 entries, 0 to 78405
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   burners         78406 non-null  object
 1   burnerParent    78406 non-null  object
 2   totalWins       78406 non-null  float64
 3   totalLosses     78406 non-null  float64
 4   totalGasEarned  78406 non-null  float64
 5   totalGasLost    78406 non-null  float64
 6   totalGames      78406 non-null  float64
 7   totalRevenue    78406 non-null  float64
dtypes: float64(6), object(2)
memory usage: 4.8+ MB

In [10]:
deploy1 = pd.read_pickle(os.path.join(DEPLOY1_FOLDER_PATH,"players.pkl"))

In [11]:
deploy1.head()

,burners,burnerParent,totalWins,totalLosses,totalGasEarned,totalGasLost,totalGames,totalRevenue
0,0x24bF54A5Ce74e589Bc192518d76b75959886346d,0xB8eb412990236ebb933675C8b5C4cc9812B69dED,2.0,3.0,0.584,0.3,5.0,0.284
1,0xfE3e6ab5d787F4099478Bbe811a740d903E219fb,0x0000000000000000000000000000000000000000,1.0,4.0,0.584,0.5,5.0,0.084
2,0x100b782936498F640c8Df54ab57bfd2186F0f002,0x4EE6a67a9DDeD0c4c74FD9Ee4E2D83D03bf50A94,0.0,5.0,0.000,0.5,5.0,-0.500
3,0x16f6AfF7A2D84B802b2ddF0F0AeD49033B69F4f9,0x0000000000000000000000000000000000000000,1.0,3.0,0.096,0.3,4.0,-0.204
4,0x6cF9E3ADF2c0FaB32C6f19c112dB62239DeBc049,0x7C898Dd66e27Cc82C87Ddbe0dB3093308DaF27fd,2.0,2.0,0.584,0.2,4.0,0.384

In [12]:
deploy1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 177 entries, 0 to 176
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   burners         177 non-null    object
 1   burnerParent    177 non-null    object
 2   totalWins       177 non-null    float64
 3   totalLosses     177 non-null    float64
 4   totalGasEarned  177 non-null    float64
 5   totalGasLost    177 non-null    float64
 6   totalGames      177 non-null    float64
 7   totalRevenue    177 non-null    float64
dtypes: float64(6), object(2)
memory usage: 11.2+ KB

In [13]:
finalPlayers = pd.concat([players, deploy1],ignore_index=True)

In [14]:
finalPlayers = finalPlayers.sort_values(["burnerParent","totalGames"], ascending = [False, False])
finalPlayers.reset_index(drop=True,inplace=True)
print(finalPlayers.info())
finalPlayers.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78583 entries, 0 to 78582
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   burners         78583 non-null  object
 1   burnerParent    78583 non-null  object
 2   totalWins       78583 non-null  float64
 3   totalLosses     78583 non-null  float64
 4   totalGasEarned  78583 non-null  float64
 5   totalGasLost    78583 non-null  float64
 6   totalGames      78583 non-null  float64
 7   totalRevenue    78583 non-null  float64
dtypes: float64(6), object(2)
memory usage: 4.8+ MB
None

,burners,burnerParent,totalWins,totalLosses,totalGasEarned,totalGasLost,totalGames,totalRevenue
0,0xeedb9220C43f29Bd807Fd2c092c0EFA841F67ED4,0xfff069C7de69b4433050E7AaeaB4BB198541DF56,1.0,4.0,0.292,1.3,5.0,-1.008
1,0x9093470d431257D665687D97F22f0Db64408E03D,0xffe52c5e9cFddd7A538c430880d7778531EB0d01,1.0,0.0,0.096,0.0,1.0,0.096
2,0x6023aE94a819F55dbeAa095f0f9787F57945327C,0xffd97359a750C4f1d809850c892aDa58e8ED69c4,1.0,1.0,0.096,0.1,2.0,-0.004
3,0x097d70f467697551CEBE1B074CA8dAcAf37075D1,0xffd43E21214D2e39F3C017a85602Dc9a7f54b23A,1.0,2.0,0.292,0.2,3.0,0.092
4,0x08498E4644A02b84a3b674150a663C3B3CBe729A,0xffb58E2364a07D2fC43C008E32d492b99EcA60f9,0.0,1.0,0.000,0.1,1.0,-0.100
5,0xCb75970cd756b4a61011e0769f2299529d7ca1C6,0xffb0A17E69CB382175503cfe0B029b179658a06A,1.0,1.0,0.096,0.1,2.0,-0.004
6,0x211287fFe9EB23B15901423A161f2a2100c2D67B,0xffa6FE7969c3B2eF11D1A7dEA26fD525B08F0540,1.0,0.0,0.194,0.0,1.0,0.194
7,0x49C2ee34Fd867855d870813a0DF8F65497e5cDd5,0xffFd91598070a2aEEC0648A5177b2a922C06FB76,0.0,3.0,0.000,0.3,3.0,-0.300
8,0xE6A58EA33cEeE090F7699Df2Bd13708757b5384F,0xffFd1e3a582B1122dCfF374eAD6AA9241b6F0A9b,1.0,5.0,0.194,0.5,6.0,-0.306
9,0x94Efd99E2A85EDdfF16F1E1B8B725A6a6F3f33c9,0xffF9D646917ba8370f997e277f6EB00C49444444,1.0,2.0,0.194,0.2,3.0,-0.006

In [15]:
finalPlayersWithParentBurner = finalPlayers[finalPlayers["burnerParent"] !="0x0000000000000000000000000000000000000000"]
print(finalPlayersWithParentBurner.info())
finalPlayersWithParentBurner.sort_values(by=["burnerParent", "totalGames"],ascending=[False,False],inplace=True)
finalPlayersWithParentBurner.head(10)

<class 'pandas.core.frame.DataFrame'>
Index: 76227 entries, 0 to 76226
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   burners         76227 non-null  object
 1   burnerParent    76227 non-null  object
 2   totalWins       76227 non-null  float64
 3   totalLosses     76227 non-null  float64
 4   totalGasEarned  76227 non-null  float64
 5   totalGasLost    76227 non-null  float64
 6   totalGames      76227 non-null  float64
 7   totalRevenue    76227 non-null  float64
dtypes: float64(6), object(2)
memory usage: 5.2+ MB
None

/tmp/ipykernel_274/3616447075.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  finalPlayersWithParentBurner.sort_values(by=["burnerParent", "totalGames"],ascending=[False,False],inplace=True)

,burners,burnerParent,totalWins,totalLosses,totalGasEarned,totalGasLost,totalGames,totalRevenue
0,0xeedb9220C43f29Bd807Fd2c092c0EFA841F67ED4,0xfff069C7de69b4433050E7AaeaB4BB198541DF56,1.0,4.0,0.292,1.3,5.0,-1.008
1,0x9093470d431257D665687D97F22f0Db64408E03D,0xffe52c5e9cFddd7A538c430880d7778531EB0d01,1.0,0.0,0.096,0.0,1.0,0.096
2,0x6023aE94a819F55dbeAa095f0f9787F57945327C,0xffd97359a750C4f1d809850c892aDa58e8ED69c4,1.0,1.0,0.096,0.1,2.0,-0.004
3,0x097d70f467697551CEBE1B074CA8dAcAf37075D1,0xffd43E21214D2e39F3C017a85602Dc9a7f54b23A,1.0,2.0,0.292,0.2,3.0,0.092
4,0x08498E4644A02b84a3b674150a663C3B3CBe729A,0xffb58E2364a07D2fC43C008E32d492b99EcA60f9,0.0,1.0,0.000,0.1,1.0,-0.100
5,0xCb75970cd756b4a61011e0769f2299529d7ca1C6,0xffb0A17E69CB382175503cfe0B029b179658a06A,1.0,1.0,0.096,0.1,2.0,-0.004
6,0x211287fFe9EB23B15901423A161f2a2100c2D67B,0xffa6FE7969c3B2eF11D1A7dEA26fD525B08F0540,1.0,0.0,0.194,0.0,1.0,0.194
7,0x49C2ee34Fd867855d870813a0DF8F65497e5cDd5,0xffFd91598070a2aEEC0648A5177b2a922C06FB76,0.0,3.0,0.000,0.3,3.0,-0.300
8,0xE6A58EA33cEeE090F7699Df2Bd13708757b5384F,0xffFd1e3a582B1122dCfF374eAD6AA9241b6F0A9b,1.0,5.0,0.194,0.5,6.0,-0.306
9,0x94Efd99E2A85EDdfF16F1E1B8B725A6a6F3f33c9,0xffF9D646917ba8370f997e277f6EB00C49444444,1.0,2.0,0.194,0.2,3.0,-0.006

In [16]:
finalPlayersWithParentBurner.sort_values(by="burnerParent").head(10) # check no empty burner

,burners,burnerParent,totalWins,totalLosses,totalGasEarned,totalGasLost,totalGames,totalRevenue
76226,0xC4d572dfe8B6D369d7F5bF40e78AAB012b5d1a67,0x000000006F457c0f8F560333d9c2877287d92a92,1.0,4.0,0.096,0.4,5.0,-0.304
76225,0x1642Aa9569511642FDc4E2085cD908F3129b9f77,0x00000008Ba1350e10F55a208C0C449F7d07be5B0,0.0,1.0,0.000,0.1,1.0,-0.100
76224,0x8c49f23f54b6307f8B5b0D49B288003C2845b2F3,0x0000001089167600c25258Da29d2e2c857ec1689,1.0,0.0,1.940,0.0,1.0,1.940
76223,0x1E5570ab680Fa67434954e973E0c8B695c255Cb8,0x000000a584697755A0378444f34FEc06229B7E38,3.0,6.0,0.582,0.6,9.0,-0.018
76222,0xe326Eb5da1003b8bCdd4C8744BF838E53bB9a50A,0x0000040f1111c5C3d2037940658Ee770BB37e0a2,2.0,1.0,0.388,0.1,3.0,0.288
76221,0x6455961d84F418a5F4574529FAcf6532d0291798,0x00000E0e2E6298505A639A340845F60a0eeA8528,0.0,1.0,0.000,0.1,1.0,-0.100
76220,0x4Ee5975FF8a66d8FA591CaE7DA2e684361070854,0x000025B47899B3fc97383a65510C8e84389B1490,1.0,7.0,0.194,0.7,8.0,-0.506
76219,0xcCB6e544Cf2b35F6057F04C9f5d7Cdca2612c417,0x000047eF8DF94434bF57B9CD3BF1D19Fd88AC910,0.0,1.0,0.000,1.0,1.0,-1.000
76218,0xe8048C7bd0BAAC6621b023F8D2C7de07AD65a104,0x00009B30097B18aD52511E469cD6d626BD3503AE,1.0,0.0,0.292,0.0,1.0,0.292
76217,0xc32029dCaC21aF5015e6A33a896F5FF4C7F81CB5,0x0000CE08fa224696A819877070BF378e8B131ACF,1.0,0.0,0.584,0.0,1.0,0.584

In [18]:
finalPlayersWithParentBurner.info()

<class 'pandas.core.frame.DataFrame'>
Index: 76227 entries, 0 to 76226
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   burners         76227 non-null  object
 1   burnerParent    76227 non-null  object
 2   totalWins       76227 non-null  float64
 3   totalLosses     76227 non-null  float64
 4   totalGasEarned  76227 non-null  float64
 5   totalGasLost    76227 non-null  float64
 6   totalGames      76227 non-null  float64
 7   totalRevenue    76227 non-null  float64
dtypes: float64(6), object(2)
memory usage: 5.2+ MB

In [20]:
finalPlayersWithParentBurner.drop_duplicates(subset="burners",inplace=True)
finalPlayersWithParentBurner.info()

<class 'pandas.core.frame.DataFrame'>
Index: 76206 entries, 0 to 76226
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   burners         76206 non-null  object
 1   burnerParent    76206 non-null  object
 2   totalWins       76206 non-null  float64
 3   totalLosses     76206 non-null  float64
 4   totalGasEarned  76206 non-null  float64
 5   totalGasLost    76206 non-null  float64
 6   totalGames      76206 non-null  float64
 7   totalRevenue    76206 non-null  float64
dtypes: float64(6), object(2)
memory usage: 5.2+ MB

/tmp/ipykernel_274/2719777128.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  finalPlayersWithParentBurner.drop_duplicates(subset="burners",inplace=True)

In [21]:
# output FinalPlayersWithBurners
finalPlayersWithParentBurner.to_pickle("finalWithParents28102023.pkl")

In [22]:
finalPlayersWithParentBurner.to_csv("finalWithParents28102023.csv",index=False)

In [23]:
# get totals for parent burner
parentBurnerStats = finalPlayersWithParentBurner.groupby("burnerParent")[["totalWins","totalLosses", "totalGasEarned", "totalGasLost", "totalGames", "totalRevenue"
                                                                         ]].sum().reset_index()
print(parentBurnerStats.info())
parentBurnerStats.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74541 entries, 0 to 74540
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   burnerParent    74541 non-null  object
 1   totalWins       74541 non-null  float64
 2   totalLosses     74541 non-null  float64
 3   totalGasEarned  74541 non-null  float64
 4   totalGasLost    74541 non-null  float64
 5   totalGames      74541 non-null  float64
 6   totalRevenue    74541 non-null  float64
dtypes: float64(6), object(1)
memory usage: 4.0+ MB
None

,burnerParent,totalWins,totalLosses,totalGasEarned,totalGasLost,totalGames,totalRevenue
0,0x000000006F457c0f8F560333d9c2877287d92a92,1.0,4.0,0.096,0.4,5.0,-0.304
1,0x00000008Ba1350e10F55a208C0C449F7d07be5B0,0.0,1.0,0.000,0.1,1.0,-0.100
2,0x0000001089167600c25258Da29d2e2c857ec1689,1.0,0.0,1.940,0.0,1.0,1.940
3,0x000000a584697755A0378444f34FEc06229B7E38,3.0,6.0,0.582,0.6,9.0,-0.018
4,0x0000040f1111c5C3d2037940658Ee770BB37e0a2,2.0,1.0,0.388,0.1,3.0,0.288
5,0x00000E0e2E6298505A639A340845F60a0eeA8528,0.0,1.0,0.000,0.1,1.0,-0.100
6,0x000025B47899B3fc97383a65510C8e84389B1490,1.0,7.0,0.194,0.7,8.0,-0.506
7,0x000047eF8DF94434bF57B9CD3BF1D19Fd88AC910,0.0,1.0,0.000,1.0,1.0,-1.000
8,0x00009B30097B18aD52511E469cD6d626BD3503AE,1.0,0.0,0.292,0.0,1.0,0.292
9,0x0000CE08fa224696A819877070BF378e8B131ACF,1.0,0.0,0.584,0.0,1.0,0.584

In [24]:
complete1Games = parentBurnerStats[parentBurnerStats["totalGames"]>0]
complete1Games.to_csv("complete1Games28102023.csv", index=False)

In [25]:
complete3Games = parentBurnerStats[parentBurnerStats["totalGames"]>2]
complete3Games.to_csv("complete3Games28102023.csv", index=False)

In [26]:
totalWins1Games = parentBurnerStats[parentBurnerStats["totalWins"]>0]
totalWins1Games.to_csv("totalWins1orMore28102023.csv", index=False)

In [27]:
countUnique = finalPlayersWithParentBurner.groupby("burnerParent")["burners"].count().to_frame().reset_index().sort_values(by="burners",ascending=False)
countUnique

                                     burnerParent  burners
31957  0x6bA85D3c435766834332a900F098c8337B1D789D       13
67181  0xca673ab5C576fBB1B7AA3E613D54EC29BD830c22        7
5124   0x11d7c9618Af6C0663872779c2813906434730dEf        7
6379   0x163F0e5eae62252F08B75B974A91FC8accc04581        6
27516  0x5c1115B1b81df25FB220Aac2c29EDCfE55419ff7        5
...                                           ...      ...
25111  0x55d45bf90Fc1Ba1cc1217Fd8d81f8DC8243839cd        1
25110  0x55d3984ED7349D6A5000B8Cf8717E001E4EfF7D8        1
25109  0x55ceb6159a2ed1bcDB01D5e9cFEB3f6277657DB5        1
25108  0x55cE5CA29Df55203FF12C5F3FFB4Dfe2b6d063b5        1
74540  0xfff069C7de69b4433050E7AaeaB4BB198541DF56        1

[74541 rows x 2 columns]